// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel shaderHandle

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> outputTexture;

[numthreads(8, 8, 1)]
void shaderHandle(uint3 id : SV_DispatchThreadID)
{
	float4 color = outputTexture[id.xy];
	color.r = 1;
	outputTexture[id.xy] = color;//outputTexture[id.xy];
}
